logLevel = "DEBUG"

defaultEntryPoints = ["http"]

[entryPoints]
    [entryPoints.http]
    address = "127.0.0.1:8080"

#    [frontends.frontend1.routes.test_1]
#    rule = "Host:http://lolcatho.st:8080/"

[web]
address = ":7878"

[file]
  [backends]
    [backends.bench]
      [backends.bench.servers.server1]
      url = "http://127.0.0.1:1030"
      [backends.bench.servers.server2]
      url = "http://127.0.0.1:1031"
  [frontends]
    [frontends.frontend1]
    backend = "bench"
