# sozu proxy test config file

command_socket = "./sock"
saved_state    = "./state.json"
log_level      = "info"
log_target     = "stdout"
command_buffer_size = 16384
worker_count = 1
handle_process_affinity = false

[http]
address = "127.0.0.1"
max_connections = 500
port = 8080
buffer_size = 16384

[https]
address = "127.0.0.1"
max_connections = 500
port = 8443
buffer_size = 16384

[applications]

[applications.MyApp]
hostname   = "lolcatho.st"
frontends = ["HTTP"] # list of proxy tags
backends  = [ "127.0.0.1:1030", "127.0.0.1:1031" ] # list of IP/port

